// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfbpkblpinsorkttdrxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYnBrYmxwaW5zb3JrdHRkcnhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NDk4MDQsImV4cCI6MjA1NjUyNTgwNH0.PSCgYe3X4RuEttWsTts6KHlU-mBukN7JJ7jgTW8h9LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);